apiVersion: v1
kind: Pod
metadata:
  name: agent-kcp
spec:
  containers:
  - name: spoke-agent
    image: quay.io/pdettori/registration
    args:
      - "/registration"
      - "agent"
      - "--cluster-name={{ .clusterName }}"
      - "--bootstrap-kubeconfig=/spoke/bootstrap/kubeconfig"
      - "--kubeconfig=/etc/kubernetes/admin.kubeconfig.unshared"
      - "--namespace=open-cluster-management-agent"
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      runAsNonRoot: true
    volumeMounts:
    - name: bootstrap-secret
      mountPath: "/spoke/bootstrap"
      readOnly: true
    - name: hub-kubeconfig
      mountPath: "/spoke/hub-kubeconfig"
    - name: spoke-kubeconfig
      mountPath: "/etc/kubernetes/admin.kubeconfig.unshared"
  - name: work-agent
    image: quay.io/open-cluster-management/work
    args:
      - "/work"
      - "agent"
      - "--spoke-cluster-name={{ .clusterName }}"
      - "--hub-kubeconfig=/spoke/hub-kubeconfig/kubeconfig"
      - "--kubeconfig=/etc/kubernetes/admin.kubeconfig.unshared"
      - "--namespace=open-cluster-management-agent"
      - "--listen=0.0.0.0:9443"
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      runAsNonRoot: true
    volumeMounts:
    - name: hub-kubeconfig
      mountPath: "/spoke/hub-kubeconfig"
    - name: spoke-kubeconfig
      mountPath: "/etc/kubernetes/admin.kubeconfig.unshared"      
  volumes:
  - hostPath:
      path: {{ .apiserverHome }}/bootstrap
      type: DirectoryOrCreate
    name: bootstrap-secret
  - hostPath:
      path: {{ .apiserverHome }}/admin.kubeconfig.unshared
      type: DirectoryOrCreate
    name: spoke-kubeconfig  
  - hostPath:      
      path: {{ .apiserverHome }}/hub
      type: DirectoryOrCreate
    name: hub-kubeconfig