apiVersion: v1
kind: Pod
metadata:
  name: agent
spec:
  containers:
  - name: spoke-agent
    image: quay.io/open-cluster-management/registration:latest
    args:
      - "/registration"
      - "agent"
      - "--cluster-name=podman2"
      - "--bootstrap-kubeconfig=/spoke/bootstrap/kubeconfig"
      - "--kubeconfig=/etc/kubernetes/admin.conf"
      - "--namespace=open-cluster-management-agent"
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      runAsNonRoot: true
    volumeMounts:
    - name: bootstrap-secret
      mountPath: "/spoke/bootstrap"
      readOnly: true
    - name: hub-kubeconfig
      mountPath: "/spoke/hub-kubeconfig"
    - name: spoke-kubeconfig
      mountPath: "/etc/kubernetes"  
  volumes:
  - hostPath:
      path: /home/ubuntu/go/src/github.com/pdettori/cymba/.kae/bootstrap
      type: DirectoryOrCreate
    name: bootstrap-secret
  - hostPath:
      path: /home/ubuntu/go/src/github.com/pdettori/cymba/.kae/
      type: DirectoryOrCreate
    name: spoke-kubeconfig  
  - hostPath:      
      path: /home/ubuntu/go/src/github.com/pdettori/cymba/.kae/hub
      type: DirectoryOrCreate
    name: hub-kubeconfig  