apiVersion: v1
kind: Pod
metadata:
  name: agent
spec:
  containers:
  - name: spoke-agent
    image: quay.io/open-cluster-management/registration
    args:
      - "/registration"
      - "agent"
      - "--cluster-name=podman3"
      - "--bootstrap-kubeconfig=/spoke/bootstrap/kubeconfig"
      - "--kubeconfig=/etc/kubernetes/admin.kubeconfig"
      - "--namespace=open-cluster-management-agent"
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      runAsNonRoot: true
    volumeMounts:
    - name: bootstrap-secret
      mountPath: "/spoke/bootstrap"
      readOnly: true
    - name: hub-kubeconfig
      mountPath: "/spoke/hub-kubeconfig"
    - name: spoke-kubeconfig
      mountPath: "/etc/kubernetes"
  # - name: work-agent
  #   image: quay.io/open-cluster-management/work
  #   args:
  #     - "/work"
  #     - "agent"
  #     - "--spoke-cluster-name=podman2"
  #     - "--hub-kubeconfig=/spoke/hub-kubeconfig/kubeconfig"
  #     - "--kubeconfig=/etc/kubernetes/admin.conf"
  #     - "--namespace=open-cluster-management-agent"
  #   securityContext:
  #     allowPrivilegeEscalation: false
  #     capabilities:
  #       drop:
  #         - ALL
  #     privileged: false
  #     runAsNonRoot: true
  #   volumeMounts:
  #   - name: hub-kubeconfig
  #     mountPath: "/spoke/hub-kubeconfig"
  #   - name: spoke-kubeconfig
  #     mountPath: "/etc/kubernetes"      
  volumes:
  - hostPath:
      path: /home/ubuntu/go/src/github.com/pdettori/cymba/.kae2/bootstrap
      type: DirectoryOrCreate
    name: bootstrap-secret
  - hostPath:
      path: /home/ubuntu/go/src/github.com/pdettori/cymba/.kcp/
      type: DirectoryOrCreate
    name: spoke-kubeconfig  
  - hostPath:      
      path: /home/ubuntu/go/src/github.com/pdettori/cymba/.kae2/hub
      type: DirectoryOrCreate
    name: hub-kubeconfig  